apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: photon-memristor-sim
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: photon-memristor-sim
  minReplicas: 2
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
